//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StreetviewRipper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StreetviewRipper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML&gt;
        ///&lt;html&gt;
        ///    &lt;head&gt;
        ///        &lt;script&gt;
        ///            window.onload = function() {
        ///                var dataPoints1 = [];
        ///                var dataPoints2 = [];
        ///                var dataPoints3 = [];
        ///                var dataPoints4 = [];
        ///            
        ///                var use2 = %USE_2%;
        ///                var use3 = %USE_3%;
        ///                var use4 = %USE_4%;
        ///
        ///                var options =  {
        ///	                animationEnabled: true,
        ///	                theme: &quot;light2&quot;,
        ///	                titl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HistogramHTML {
            get {
                return ResourceManager.GetString("HistogramHTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libraries/Classify/.
        /// </summary>
        internal static string Library_Classifier {
            get {
                return ResourceManager.GetString("Library_Classifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libraries/EXR2HDR/.
        /// </summary>
        internal static string Library_EXR2HDR {
            get {
                return ResourceManager.GetString("Library_EXR2HDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libraries/EXR2LDR/.
        /// </summary>
        internal static string Library_EXR2LDR {
            get {
                return ResourceManager.GetString("Library_EXR2LDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libraries/HDR2EXR/.
        /// </summary>
        internal static string Library_HDR2EXR {
            get {
                return ResourceManager.GetString("Library_HDR2EXR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libraries/HDR2Float/.
        /// </summary>
        internal static string Library_HDR2Float {
            get {
                return ResourceManager.GetString("Library_HDR2Float", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libraries/HDRConverter/.
        /// </summary>
        internal static string Library_HDRConverter {
            get {
                return ResourceManager.GetString("Library_HDRConverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libraries/LDR2HDR_Upscaler/.
        /// </summary>
        internal static string Library_HDRUpscaler {
            get {
                return ResourceManager.GetString("Library_HDRUpscaler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libraries/ImageMagick/.
        /// </summary>
        internal static string Library_IM {
            get {
                return ResourceManager.GetString("Library_IM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libraries/LDR2HDR/.
        /// </summary>
        internal static string Library_LDR2HDR {
            get {
                return ResourceManager.GetString("Library_LDR2HDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libraries/PBRT/.
        /// </summary>
        internal static string Library_PBRT {
            get {
                return ResourceManager.GetString("Library_PBRT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output/Histograms/.
        /// </summary>
        internal static string Output_Histogram {
            get {
                return ResourceManager.GetString("Output_Histogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output/Images/.
        /// </summary>
        internal static string Output_Images {
            get {
                return ResourceManager.GetString("Output_Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] pano2fisheye {
            get {
                object obj = ResourceManager.GetObject("pano2fisheye", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
